config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/tag_search', to: 'tags#search'

  delete '/tags/:id', to: 'tags#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :subject_posts,       only: [:create, :show, :index, :destroy]
  resources :reply_posts,         only: [:create, :show, :index, :destroy]
  resources :feedback_posts,      only: [:create, :show, :destroy, :edit, :index, :update]

  resources :tags,                only: [:destroy, :create] do
    get 'subject_posts', to: 'subject_posts#search'
  end

    delete 'tags/:id', to: 'tags#destroy'
    post 'tags/create', to: 'tags#create'

    #簡単ログイン用のroute
    post '/guest', to: 'guest_sessions#create'

  #開発環境でメールを確認する
  #http://localhost:3000/letter_openerにアクセス
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @subject_post = current_user.subject_posts.build if logged_in?
      @subject_posts = current_user.subject_feed.page(params[:page]).per(10)

      @tag = Tag.new

      @reply_post = current_user.reply_posts.build if logged_in?
      @reply_posts = current_user.reply_feed.page(params[:page]).per(10)

      @feedback_post = current_user.feedback_posts.build if logged_in?
      @feedback_posts = current_user.feedback_feed.page(params[:page]).per(10)
    end
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "LinGoChanって何") %>


<div class = "about_container row">

  <div class = "about_body col-md-12">

    <h1 class = "about_title">LinGoChanって何？</h1>

    <p>LinGoChanとは3種類の投稿を使って日本語を学べるサイトです</p>

    <div class = "about_head">

      <h2 class = "about_quasititle">3つの投稿手段で日本語を学ぼう！</h2>

      <div class = "about_statements">
        <p class = about_statement>1, お題</p>

        <p class = about_statement>2, ひとこと</p>

        <p class = about_statement>3, フィードバック</p>
      </div>

    </div>

    <div class = "about_subject_post about_each_post">

      <p  class = "about_quasiquasititle">1, 「お題」を投稿しよう！</p>
      <%= image_tag("subject_post.png", class: 'about_size', alt: "LimGoChan-subject_post") %>

    </div>


    <div class = "about_reply_post about_each_post">
      <p  class = "about_quasiquasititle">1, お題にたいして「ひとこと」を書こう！</p>
      <%= image_tag("reply_post.png", class: 'about_size', alt: "LimGoChan-reply_post")%>

    </div>

    <div class = "about_feedback_post about_each_post">
      <p  class = "about_quasiquasititle">3, 「ひとこと」にたいして「フィードバック」をしよう！</p>
      <%= image_tag("feedback_post.png", class: 'about_size', alt: "LimGoChan-feedback_post")%>
    </div>

      <p  class = "about_quasiquasititle">「フィードバック」は編集したり、削除したりできます</p>
    <div class = "about_subject_post">
      <%= image_tag("edit_delete.png", class: 'about_size', alt: "LimGoChan-edit_delete")%>
    </div>

  </div>

</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <% breadcrumb :root%>
  <%= render "shared/breadcrumbs" %>

    <div class="row common_row upper_info_row">
      <aside class="col-md-6 common_col upper_info">
        <section class="user_info upper_user_info">
          <%#ユーザーの画像%>
            <%= render 'shared/user_info', user: current_user %>
        </section>
      </aside>

      <aside class="col-md-6 common_col upper_post">
        <section class="subject_posts_form">
          <%= render 'shared/subject_posts_form' %>
        </section>
      </aside>
    </div>

    <div class="item_field">
        <%= render 'shared/tabpage' %>
    </div>


<% else %>
  <div class="row landing_container">
    <div class = "col-md-12 landing">
      <h1 class = main_title>LinGoChan</h1>
      <div class = mongon>
        <p>誰かが画像を投稿し</p>
        <p>誰かがコメントを残し</p>
        <p>誰かがフィードバックしてくれる</p>
      </div>
      <p class= "kimezerifu">全く新しい日本語学習アプリ</p>
      <%= link_to "いますぐ始める！", signup_path, class: "btn btn-lg custom_button" %>
      <%= link_to "LinGoChanって何?", about_path, class: "btn btn-lg custom_button" %>
      <%= button_to "ゲストユーザーとしてログイン", guest_path, method: :post, class: 'btn btn-success guest_button' %>
    </div>
  </div>
<% end %>