config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/tag_search', to: 'tags#search'

  delete '/tags/:id', to: 'tags#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :subject_posts,       only: [:create, :show, :index, :destroy]
  resources :reply_posts,         only: [:create, :show, :index, :destroy]
  resources :feedback_posts,      only: [:create, :show, :destroy, :edit, :index, :update]

  resources :tags,                only: [:destroy, :create] do
    get 'subject_posts', to: 'subject_posts#search'
  end

    delete 'tags/:id', to: 'tags#destroy'
    post 'tags/create', to: 'tags#create'

    #簡単ログイン用のroute
    post '/guest', to: 'guest_sessions#create'

  #開発環境でメールを確認する
  #http://localhost:3000/letter_openerにアクセス
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/subject_post.rb
class SubjectPost < ApplicationRecord
  mount_uploader :img, ImgUploader

#投稿用の関連付け
  has_many :reply_posts, dependent: :destroy
  belongs_to :user

#タグ用の関連付け
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps

  #postの順番を降順にする
  default_scope -> { order(created_at: :desc) }
  mount_uploader :img, ImgUploader
  validates :user_id, presence: true
  validates :img, presence: { message: '画像を選択してください。' }

  #画像のサイズのためのバリデーションprivate以下に定義
  validate  :img_size


  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end

  private
# アップロードされた画像のサイズをバリデーションする
    def img_size
      if img.size > 5.megabytes
        errors.add(:img, "画像は5MB以下にしてください")
      end
    end

end

app/views/shared/_admin_delete_area.html.erb
<div class = "admin_area">

  <% if posts == "subject_posts" %>
    <% if current_page?("/subject_posts/#{post.id}") %>
    <span class = "delete">
      <% if current_user.admin? %>
        <%= button_to "消去", post, {method: :delete, class: "general_button",
                                data: { confirm: "本当に消去してもいいですか？" }, } %>
      <% end %>
    </span>
  <% end %>

  <% elsif posts == "reply_posts" %>
    <% if current_page?("/reply_posts/#{post.id}") %>
    <span class = "delete">
      <% if current_user.admin? %>
        <%= button_to "消去", post, {method: :delete, class: "general_button",
                                data: { confirm: "本当に消去してもいいですか？" }, } %>
      <% end %>
    </span>
  <% end %>

  <% elsif posts == "feedback_posts" %>
    <% if current_page?("/feedback_posts/#{post.id}") %>
    <span class = "delete">
      <% if current_user.admin? %>
        <%= button_to "消去", post, {method: :delete, class: "general_button",
                                data: { confirm: "本当に消去してもいいですか？" }, } %>
      <% end %>
    </span>
   <% end %>

<% end %>


</div>

app/views/shared/_breadcrumbs.html.erb
<%= breadcrumbs separator: " &rsaquo; ", class: "breadcrumbs-list" %>

app/views/shared/_feedback_posts_form.html.erb

<%= form_for(@feedback_post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class = "row">
    <div class="field col-md-12" "フィードバック">
      <div class = "letter_counter">
        <b>残り</b>：<span class="feedback_count"></span>文字
      </div>
      <%= f.text_area :content, placeholder: "フィードバックを書いてください" %>
    </div>
  </div>
<%= f.hidden_field :reply_post_id, value: @reply_post.id %>
  <%= f.submit "投稿する！", class: "btn custom_button" %>
<% end %>

app/views/shared/_just_tag_field.html.erb

<div class = tag_field_container>

  <div class = tag_explanation>
    <p>"スペースを入力することで複数のタグを付けることができます。</p>
  </div>
  <div class = "tag_field">
      <%= f.text_field :tag_name %>
  </div>
</div>

app/views/shared/_post_image.html.erb
<%#投稿の左側にある顔写真%>
<span class = "post_image_unit">
  <%= link_to gravatar_for(post.user, size: 50), post.user, {class: "user_image"} %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
</span>

app/views/shared/_reply_feed.html.erb
<% if @reply_posts.present? %>
  <div class="row sublect_posts">
    <% @reply_posts.each do |reply_post| %>
    <div class = "col-xl-6 post_item">
      <%= render "reply_posts/reply_post", reply_post: reply_post %>
    </div>
    <% end %>
  </div>
  <%= paginate @reply_posts %>

<% else %>
  <p>まだ「ひとこと」は投稿されていません</p>
<% end %>

app/views/shared/_reply_posts_form.html.erb
<%= form_for(@reply_post) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  <div class = "row">
    <div class="field col-md-12" "ひとこと！">
      <div class = "letter_counter">
        <b>残り</b>：<span class="reply_count"></span>文字
      </div>
      <%= f.text_area :content, placeholder: "お題に対して一言..." %>
    </div>
  </div>
  <%= f.hidden_field :subject_post_id, value: @subject_post.id %>
  <%= f.submit "投稿する！", class: "btn custom_button"%>
<% end %>

app/views/shared/_subject_post_tag_list.html.erb
<div class = "tag_list_container">
<span class = "tag_list_name"> タグリスト: </span>

<br>

<span class = "tag_list">
<ul>
<% if subject_post.tags.present? %>
  <% subject_post.tags.each do |list| %>
    <span class = "tag_set">
      <li class = "tag_align">
        <%= link_to list.tag_name, "#", {class: "tag_unit"} %>
        <% if logged_in? %>
          <%= button_to '×', "/tags/#{list.id}", {method: :delete, class: "tag_delete_button", form: {style: 'display:inline;'}} %>
        <% end %>
      </li>
    </span>
      <%#= "(#{list.subject_posts.count})" %>
  <% end %>
<% end %>
</ul>
</span>
</div>

app/views/shared/_tab_contents.html.erb
<%#タブの下側homeとuser#show用%>

<div class="tab-content panel_area">
  <div id="subject_posts" class="tab-pane active tab_panel">

    <%#お題投稿のタブ%>
      <% if current_page?(root_path) %>
        <h3 class = "title_letter">投稿したお題一覧</h3>
        <%= render 'shared/subject_feed' %>
      <% else %>
          <h3 class = "title_letter"><%= @user.name %>のお題
            <% if @user.subject_posts.any? %>
              (<%= @user.subject_posts.count %>)
            <% end %>
          </h3>
            <div class = all_posts_container>
              <%= render "shared/subject_feed", subject_posts: @user.subject_posts %>
            </div>
      <% end %>
  </div>

  <div id="reply_posts" class="tab-pane tab_panel">
    <%#一言の投稿のタブの中身%>
      <% if current_page?(root_path) %>
        <h3 class = "title_letter">投稿したひとこと一覧</h3>
        <%= render 'shared/reply_feed' %>
      <% else %>
        <h3 class = "title_letter"><%= @user.name %>のひとこと
          <% if @user.reply_posts.any? %>
             (<%= @user.reply_posts.count %>)
          <% end %>
        </h3>
        <div class = all_posts_container>
          <%= render "shared/reply_feed", reply_posts: @user.reply_posts %>
        </div>
      <% end %>
  </div>

  <div id="feedback_posts" class="tab-pane tab_panel">
    <%#フィードバックタブの中身%>
      <% if current_page?(root_path) %>
        <h3 class = "title_letter">投稿したフィードバック一覧</h3>
        <%= render 'shared/feedback_feed' %>
      <% else %>
        <h3 class = "title_letter"><%= @user.name %>のフィードバック
          <% if @user.feedback_posts.any? %>
            (<%= @user.feedback_posts.count %>)
          <% end %>
        </h3>
        <div class = all_posts_container>
          <%= render "shared/feedback_feed", feedback_posts: @user.feedback_posts %>
        </div>
      <% end %>
  </div>
</div>

<div class = "homepage-title under_tub_title">
</div>

app/views/shared/_tab_switch.html.erb
  <!-- 上部のタブの部分 -->

<main class="p-3">
  <ul class="nav nav-tabs tab_area">
    <li class="nav-item tab1_label">
      <a href="#subject_posts" class="nav-link active tab_a" data-toggle="tab">お題</a>
    </li>
    <li class="nav-item tab2_label">
      <a href="#reply_posts" class="nav-link tab_a" data-toggle="tab">ひとこと</a>
    </li>
    <li class="nav-item tab3_label">
      <a href="#feedback_posts" class="nav-link tab_a" data-toggle="tab">フィードバック</a>
    </li>
  </ul>

app/views/shared/_tabpage.html.erb
<%#homeとuserページ共通テンプレート%>

<div class = tab_field>

  <!-- 上部のタブの部分 -->
  <%= render 'shared/tab_switch'%>

    <!-- 内容部分 -->
  <%= render 'shared/tab_contents'%>

</div>

app/views/shared/_tag_checkbox.html.erb
<div class = "tag">
<div class = "tag_container">

  <%= form_for @tag do |f| %>
      <div class='form-group'>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :tag_name) do |tag| %>
              <div class='form-check'>
                  <%= tag.label class: 'form-check-label' do %>

                      <%= tag.check_box class: 'form-check-input' %>

                      <%= tag.text %>
                  <% end %>
              </div>
          <% end %>
      </div>

      <%= f.submit '保存する！', class: 'btn btn-primary' %>
  <% end %>

</div>
</div>



<%= form_for(@subject_post.tag) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field" "フィードバック">
    <%= f.text_area :content, placeholder: "フィードバックを書いてください" %>
  </div>
<%= f.hidden_field :reply_post_id, value: @reply_post.id %>
  <%= f.submit "タグの登録をする！", class: "btn btn-primary" %>
<% end %>

app/views/shared/_timestamp.html.erb
<div id = "timestamp">
    <span class="timestamp">
    <%= time_ago_in_words(post.created_at) %>前
    </span>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(user, size: 50), user, {class: "user_image"} %>
<h1><%= user.name %></h1>

<% if current_page?(root_path) %>
  <p>
  <span><%= button_to "プロフィールを見る！", user, {method: :get, class: "ungeneral_button",form: {style: 'display:inline;'}} %></span>
  </p>
<% elsif current_user?(@user) %>
  <p>
  <span><%= button_to "自己紹介を書いてみる！", edit_user_path(current_user), {method: :get, class: "ungeneral_button",form: {style: 'display:inline;'}} %></span>
  </p>
<% else %>
  <p></p>
<% end %>

<span clas = "post_count">お題投稿数:<%= user.subject_posts.count %></span>
<span clas = "post_count">ひとこと投稿数:<%= user.reply_posts.count %></span>
<span clas = "post_count">フィードバック投稿数:<%= user.feedback_posts.count %></span>