config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/tag_search', to: 'tags#search'

  delete '/tags/:id', to: 'tags#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :subject_posts,       only: [:create, :show, :index, :destroy]
  resources :reply_posts,         only: [:create, :show, :index, :destroy]
  resources :feedback_posts,      only: [:create, :show, :destroy, :edit, :index, :update]

  resources :tags,                only: [:destroy, :create] do
    get 'subject_posts', to: 'subject_posts#search'
  end

    delete 'tags/:id', to: 'tags#destroy'
    post 'tags/create', to: 'tags#create'

    #簡単ログイン用のroute
    post '/guest', to: 'guest_sessions#create'

  #開発環境でメールを確認する
  #http://localhost:3000/letter_openerにアクセス
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/feedback_post.rb
class FeedbackPost < ApplicationRecord
  belongs_to :user
  belongs_to :reply_post

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :reply_post_id, presence: true

  validates :content, presence: true, length: { maximum: 280 }
end

app/controllers/feedback_posts_controller.rb
class FeedbackPostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :edit]
  before_action :correct_user, only: [:edit, :update]
  before_action :correct_user_or_admin_user, only: [:destroy]

  def create
    @feedback_post = current_user.feedback_posts.build(feedback_post_params)
    if @feedback_post.save
      flash[:success] = "投稿完了!"
      redirect_to root_url
    else
      @feedback_feed_items = []
      flash[:danger] = '投稿に失敗しました'
      redirect_to root_url
      #render 'static_pages/home' renderではurlがfeedback_postsのままになる。
    end
  end

  def destroy
    @feedback_post.destroy
    flash[:success] = "投稿を消去しました"
    redirect_to root_url
  end

  def edit
    @feedback_post = FeedbackPost.find(params[:id])
  end

  def update
    @feedback_post = FeedbackPost.find(params[:id])
    if @feedback_post.update_attributes(feedback_post_params)
      flash[:success] = "投稿内容を変更しました！"
      redirect_to @feedback_post
    else
      flash[:danger] = '投稿の内容を変更できませんでした。'
      render 'edit'
    end
  end

  def index
    @feedback_posts = FeedbackPost.all.page(params[:page]).per(10)
  end

  def show
    @feedback_post = FeedbackPost.find(params[:id])
  end

private
  def feedback_post_params
  params.require(:feedback_post).permit(:content, :subject_post_id, :reply_post_id)
  end

  def correct_user
      @feedback_post = current_user.feedback_posts.find_by(id: params[:id])
      redirect_to root_url if @feedback_post.nil?
  end

  def correct_user_or_admin_user
    @feedback_post = current_user.feedback_posts.find_by(id: params[:id])
    admin_boolean = current_user.admin?
    if admin_boolean == true
      @feedback_post = FeedbackPost.find_by(id: params[:id])
    end
    redirect_to root_url if @feedback_post.nil? && admin_boolean == false
  end
end

app/helpers/feedback_posts_helper.rb
module FeedbackPostsHelper
end

app/views/feedback_posts/_feedback_post.html.erb

  <div class = "each_post_container">

    <div class = "feedback_reply_subject_post">
          <%#feedback_postのsubject_postとreply_postの部分%>
          <%= render "/reply_posts/reply_post", reply_post: feedback_post.reply_post  %>
    </div>

    <div class = "feedback_post">
      <div id="feedback_post-<%= feedback_post.id %>">

      <div class = "post_image">
        <%= render 'shared/post_image', post: feedback_post %>
        <span>のフィードバック</span>
      </div>
  <br>
        <div class = "feedback_content_box">
          <div class = "feedback_content">
            <%= feedback_post.content %>
          </div>
  <br>
          <%# タイムスタンプ(～前みたいなん)%>
          <%= render 'shared/timestamp', post: feedback_post %>
        </div>

      <%# もし今のページがsubject_postのshowのページで、現在のユーザーが管理者のとき消せる %>
        <%= render 'shared/admin_delete_area', {post: feedback_post, posts: "feedback_posts"} %>


  <%#もし、フィードバックのshow(詳細ページ)でcurrent_userだったら消去と編集、それ以外だったら「詳しく見る」を表示%>
        <div class = detail_or_edit_delete>
          <% if current_page?("/feedback_posts/#{feedback_post.id}") %>
            <span class = "delete">
              <% if current_user?(@feedback_post.user) && !current_user.admin? %>
                <%= button_to "消去", @feedback_post, {method: :delete, class: "general_button", data: { confirm: "本当に消去してもいいですか？" }} %>
              <% end %>
            </span>

            <span class = "edit">
              <% if current_user?(@feedback_post.user) %>
                <%= button_to "編集", edit_feedback_post_path(@feedback_post), {method: :get, class: "general_button"} %>
              <% end %>
            </span>
          <% else %>
            <span class = "details">
              <%= button_to "詳しく見る", feedback_post_path(feedback_post), {method: :get, class: "general_button"}%>
            </span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/feedback_posts/edit.html.erb
<% provide(:title, "Edit feedback_post") %>
<h1>フィードバックの編集</h1>

<div class = "reply_post-form">
  <%= render "/reply_posts/reply_post", reply_post: @feedback_post.reply_post %>
</div>

  <div class = "feedback_form">
    <%= form_for(@feedback_post) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    <div class = "row">
      <div class="field" "フィードバック">
        <div class = "letter_counter">
          <b>残り</b>：<span class="feedback_count"></span>文字
        </div>
        <%= f.text_area :content, placeholder: "フィードバックを書いてください" %>
      </div>
    </div>
      <%= f.submit "投稿する！", class: "btn custom_button" %>
    <% end %>
  </div>

app/views/feedback_posts/index.html.erb
<%# お題、一言、フェードバックの塊の羅列 %>

<% provide(:title, 'All feedback_posts') %>

<% breadcrumb :feedback_post%>
<%= render "shared/breadcrumbs" %>

<h1>フィードバックの一覧</h1>

<% if @feedback_posts.present? %>

  <%= paginate @feedback_posts %>

  <ul class="feedback_posts">
    <% @feedback_posts.each do |feedback_post| %>
      <%= render "/feedback_posts/feedback_post", feedback_post: feedback_post%>
    <% end %>
  </ul>

  <%= paginate @feedback_posts %>

<% else %>

  <p>まだ投稿はありません</p>

<% end %>

app/views/feedback_posts/show.html.erb
<% provide(:title, @feedback_post.id) %>

<% breadcrumb :feedback_post_show, @feedback_post%>
<%= render "shared/breadcrumbs" %>

<div class = "main post-show">

  <% if @feedback_post.present? %>

    <div class = "show-title under_tub_title">
      <h1><%= link_to @feedback_post.user.name, user_path(@feedback_post.user)%>のフィードバック</h1>
    </div>

    <%= render "/feedback_posts/feedback_post", feedback_post: @feedback_post%>

  <% else %>
    <p>まだ投稿はありません</p>
  <% end %>

</div>