config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get    '/tag_search', to: 'tags#search'

  delete '/tags/:id', to: 'tags#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :subject_posts,       only: [:create, :show, :index, :destroy]
  resources :reply_posts,         only: [:create, :show, :index, :destroy]
  resources :feedback_posts,      only: [:create, :show, :destroy, :edit, :index, :update]

  resources :tags,                only: [:destroy, :create] do
    get 'subject_posts', to: 'subject_posts#search'
  end

    delete 'tags/:id', to: 'tags#destroy'
    post 'tags/create', to: 'tags#create'

    #簡単ログイン用のroute
    post '/guest', to: 'guest_sessions#create'

  #開発環境でメールを確認する
  #http://localhost:3000/letter_openerにアクセス
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class = "container">
    <ul class = "footer_ul">
      <li><%= link_to "ホーム", root_path, {class: "footer-menu"} %></li>
      <li><%= link_to "LinGoChanって何?", about_path, {class: "footer-menu"} %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-md navbar-dark" >
  <div class="container">
    <%= link_to image_tag("LinGoChan.png", alt: "LimGoChan"),
                  root_path, id: "logo"%>
    <nav id = "menu">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path, {class: "main-menu"} %></li>
        <li><%= link_to "概要", about_path, {class: "main-menu"} %></li>

      <% if logged_in? %>
        <li><%= link_to "ユーザー", users_path, {class: "main-menu"} %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle main-menu" data-toggle="dropdown">
              投稿 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= button_to "お題を投稿する", root_path, {method: :get, class: "drop_button"} %></li>
              <li><%= button_to "一言を書く", subject_posts_path, {method: :get, class: "drop_button"} %></li>
              <li><%= button_to "フィードバックをする", reply_posts_path, {method: :get, class: "drop_button"} %></li>
              <li><%= button_to "投稿一覧を見る", feedback_posts_path, {method: :get, class: "drop_button"} %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle account-drop main-menu" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">

              <div class = "current_user">
                <%= render 'layouts/user_info_header' %>
              </div>

              <li><%= button_to "プロフィール", current_user, {method: :get, class: "drop_button"} %></li>
              <li><%= button_to "プロフィールの設定", edit_user_path(current_user), {method: :get, class: "drop_button"} %></li>
              <li class="divider"></li>
              <li>
                <%= button_to "ログアウト", logout_path, {method: :delete, class: "drop_button"} %>
              </li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "ログイン", login_path, {class: "main-menu"} %></li>
        <% end %>
      </ul>

    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_user_info_header.html.erb
<div class = "user_image" >
  <%= link_to gravatar_for(current_user, size: 50), current_user %>
</div>

<p class = "user_name_header" >
  <%= current_user.name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= render("layouts/shim") %>
  </head>

  <body>
    <%= render("layouts/header") %>

  <%# 背景画像のための記述 %>
    <div class = "main_contents",
     style="background-image: url(<%= asset_pack_path 'media/images/background_img.png' %>); background-size: cover; background-repeat: repeat-y">

  <%#ロードアニメーションのための記述%>
      <body class="is-slide" id="page-animate">

      </body>
  <%#ここまで%>

      <div class="container main_cantainer">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>

        <%= yield %>
      </div>

        <%= render("layouts/footer")%>
        <%= debug(params) if Rails.env.development? %>

    </div>
  </body>

</html>